### ISSUE TITLE
DB warnings when adding dependencies

### ISSUE THREAD

**Issue by mchurchward** [kyro46/moodle-mod_questionnaire#1]
Hi -
Playing with your new code, I received the following warning:

```
Did you remember to make the first column something unique in your call to get_records? Duplicate value '65' found in column 'adv_dependquestion'.

    line 1103 of /lib/dml/mysqli_native_moodle_database.php: call to debugging()
    line 1380 of /lib/dml/moodle_database.php: call to mysqli_native_moodle_database->get_records_sql()
    line 1331 of /lib/dml/moodle_database.php: call to moodle_database->get_records_select()
    line 975 of /mod/questionnaire/locallib.php: call to moodle_database->get_records()
    line 999 of /mod/questionnaire/classes/question/base.php: call to questionnaire_check_page_breaks()
    line 294 of /mod/questionnaire/questions.php: call to mod_questionnaire\question\base->form_update()
```

**Comment by kyro46** [comment]
Thank you for your feedback! 

This message originates from the part, where consecutive dependencies are to be identified. I wanted to compare advanced dependency arrays without further preparing operations between two questions, so the records were loaded without the DB-ID. The arrays contain only the records with adv_dependquestion, adv_dependchoice and adv_dependlogic and are directly checked for equality.

To stop moodle from stumbling against this, I will load them with the ID-column and strip it of the array afterwards.
